name: Merge Upstream Changes

on:
  schedule:
    - cron: '0 0 */2 * *'  # Run every 2 days
  workflow_dispatch:  # Allows manual trigger

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the local repo
        uses: actions/checkout@v4

      - name: Configure git to ignore changes in specific files
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          echo "README.md merge=ours" >> .gitattributes
          echo "LICENSES/* merge=ours" >> .gitattributes
          echo "workflows/* merge=ours" >> .gitattributes
          echo "LICENSE.md merge=ours" >> .gitattributes
          git add .gitattributes
          git commit -m "Set our merge strategy for specific files."

      - name: Fetch the upstream repo
        run: |
          git remote add upstream https://github.com/run-llama/create-llama.git
          git fetch upstream

      - name: Fetch the latest tag from the upstream repo
        id: get_latest_tag
        run: |
          latest_tag=$(git ls-remote --tags https://github.com/run-llama/create-llama.git | awk '{print $2}' | cut -d '/' -f 3 | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
          echo "::set-output name=latest_tag::$latest_tag"

      - name: Merge upstream changes from latest tag
        run: |
          latest_tag="${{ steps.get_latest_tag.outputs.latest_tag }}"
          git merge --allow-unrelated-histories "upstream/$latest_tag" -X theirs 
          git checkout HEAD -- README.md LICENSES/
          git commit -m "Merge upstream changes from tag $latest_tag"

      - name: Generate random branch name
        id: random_branch
        run: echo "::set-output name=branch::merge-upstream-$(date +%s | sha256sum | base64 | head -c 8 ; echo)"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: "Merge upstream changes"
          branch: ${{ steps.random_branch.outputs.branch }}
          title: "Merge Upstream Changes"
          body: |
            This pull request merges the latest changes from the upstream repository.
            Please review and merge manually.
