name: Merge newes upstreaming Tag 

on:
  schedule:
    - cron: '0 0 */2 * *'  # Run every 2 days
  workflow_dispatch:  # Allows manual trigger

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the local repo
        uses: actions/checkout@v4

      - name: Configure git to ignore changes in specific files
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          echo "README.md merge=ours" >> .gitattributes
          echo "LICENSES/* merge=ours" >> .gitattributes
          echo "workflows/* merge=ours" >> .gitattributes
          echo "LICENSE.md merge=ours" >> .gitattributes
          git add .gitattributes
          git commit -m "Set our merge strategy for specific files."

      - name: Fetch the upstream repo
        run: |
          git remote add upstream https://github.com/run-llama/create-llama.git
          git fetch upstream --tags

      - name: Get latest tag
        id: latest_tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "::set-output name=tag::$latest_tag"

      - name: Merge upstream changes
        run: |
          # Temporarily allowing empty commits in case of no changes
          git merge --allow-unrelated-histories upstream/${{ steps.latest_tag.outputs.tag }} -X theirs --no-commit
          git checkout HEAD -- README.md LICENSES/
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Merge upstream Tag changes"
          fi

      - name: Generate random branch name
        id: random_branch
        run: echo "::set-output name=branch::merge-TAG-$${{ steps.latest_tag.outputs.tag }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: "Merge upstream Tag changes"
          branch: ${{ steps.random_branch.outputs.branch }}
          title: "Merge the lastest Tag of the Upstream"
          body: |
            This pull request merges the latest changes from the upstream repository.
            Please review and merge manually.
